moonstream-to/frontend

- pages/terminus/index.tsx
- src/components/ContractRow.tsx
- src/components/PoolDetailsRow.tsx
- src/components/TerminusContractView.tsx
- src/components/TerminusPoolView.tsx
- src/components/TerminusPoolsList.tsx
- src/components/TerminusPoolsListItem.tsx
> Terminus page

- pages/_app.tsx
- pages/index.tsx
- pages/terminus/index.tsx
- src/components/BreadcrumbView.tsx
- src/components/ChainSelector.tsx
- src/components/ContractRow.tsx
- src/components/FeatureCard.tsx
- src/components/Footer.tsx
- src/components/Navbar.tsx
- src/components/PoolDetailsRow.tsx
- src/components/Spinner/Spinner.tsx
- src/components/TerminusContractView.tsx
- src/components/TerminusPoolView.tsx
- src/components/TerminusPoolsList.tsx
- src/components/TerminusPoolsListItem.tsx
- src/components/TerminusPoolsListView.tsx
- src/components/layout.tsx
- src/contexts/Web3Context/context.ts
- src/contexts/Web3Context/index.tsx
- src/hooks/useLink.ts
Errors handling, filter, creating new pool, edit URI
> Terminus page improvements

- pages/airdrop/index.tsx
- src/components/Navbar.tsx
- src/hooks/useMoonToast.tsx
- src/theme/breakpoints/index.ts
- src/theme/index.ts
Adding our custom toast;
Improve responsiveness of Navbar  and Airdrop
> Airdrop improvements

- src/components/gofp/GoFPMetadataPanel.tsx
- src/components/gofp/GoFPPathCard.tsx
- src/hooks/useGofpConract.ts
> Improving lore display in GoFP.

- src/components/gofp/GoFPAddCharPanel.tsx
- src/components/gofp/GoFPSessionPanel.tsx
- src/hooks/useGofpConract.ts
> Merging GoFP getApprovalForAll checks from play branch.

- pages/minigames/index.tsx
- src/contexts/GoFPContext/gofpReducer.ts
- src/contexts/GoFPContext/index.tsx
Read contract address from router.query
> read contract address from router.query

- pages/games/garden/index.tsx
- pages/worlds/greatwyrm/inventory/index.tsx
Moved garden page to games/garden and Great Wyrm inventory to worlds/greatwyrm/inventory per Neeraj's suggestion.
> Moving greatwyrm inventory and garden of forking paths session pages.

- src/components/BreadcrumbView.tsx
> fix breadcrumb

- pages/index.tsx
> Updating portal home page links to GoFP.

- src/components/gofp/GoFPSessionPanel.tsx
> Fixing issue that appeared when we added session lore.

- pages/worlds/greatwyrm/inventory/index.tsx
- pages/worlds/greatwyrm/types.ts
- src/components/TextWithPopup.tsx
- src/components/nft/NFTCard.tsx
- src/components/nft/NFTList.tsx
> Spy mode to inventory. Fetch characters staked into GW sessions.

- src/components/DropperClaimView.tsx
- src/components/DropperContractView.tsx
> handling web3 timeout

- src/components/gofp/GoFPMetadataPanel.tsx
> GoFP path metadata should render as markdown.

- src/components/DropperClaimView.tsx
Hiding Activate button when drop is not in admin list
> hide activate button

- src/hooks/useDrops.ts
Fixing admin claims not loading when 'show' button clicked
> fix query not rerunning

- src/hooks/useDrops.ts
> adding query dependency

- pages/index.tsx
Adding dropper feature card to home page
> Dropper feature card

- pages/games/garden/sessions.tsx
- pages/index.tsx
- src/components/TextWithPopup.tsx
- src/components/gofp/GoFPSessionCard.tsx
- src/components/nft/NFTCard.tsx
- src/contexts/Web3Context/context.ts
- src/contexts/Web3Context/index.tsx
- src/hooks/useGofpConract.ts
- src/types.d.ts
- src/types/Moonstream.ts
> Adding GoFP session listing page and a few other tweaks to GoFP.

- pages/_app.tsx
> adding GA script

- pages/worlds/greatwyrm/inventory/index.tsx
- src/components/RadioFilter.tsx
- src/components/SpyModeInput.tsx
- src/components/nft/NFTList.tsx
- src/components/nft/TerminusList.tsx
> Adding GW tokens to inventory page.

- src/components/terminus/TerminusView.tsx
fixing  empty local storage error
> fix missing LS item

- pages/_document.tsx
- public/robots.txt
> Robots file

- pages/tokens/index.tsx
> removing dev link

- portal/pages/status/index.tsx
- portal/src/components/Account.tsx
- portal/src/components/Landing.tsx
- portal/src/components/NavbarLanding.tsx
- portal/src/components/Status/StatusRow.tsx
- portal/src/components/analytics/AnalyticsView.tsx
fixing some responsiveness issues on status and analytics pages
> Fix responsive

- portal/src/components/ClaimantsView.tsx
- portal/src/components/NewClaimantView.tsx
- portal/src/components/ParamInput.tsx
- portal/src/components/analytics/AnalyticsABIView.tsx
- portal/src/components/analytics/AnalyticsAddressesList.tsx
- portal/src/components/analytics/AnalyticsAddressesListItem.tsx
- portal/src/components/analytics/AnalyticsAddressesView.tsx
- portal/src/components/analytics/AnalyticsNewAddressView.tsx
- portal/src/components/analytics/AnalyticsQueryParameters.tsx
- portal/src/components/analytics/AnalyticsQueryView.tsx
- portal/src/components/analytics/AnalyticsSmartContractDetails.tsx
- portal/src/components/analytics/AnalyticsSmartContractView.tsx
- portal/src/components/analytics/AnalyticsView.tsx
- portal/src/components/analytics/validateParameters.ts
- portal/src/components/dropper/ActivateClaimButton.tsx
- portal/src/components/dropper/ChainDataEditSection.tsx
- portal/src/components/dropper/DBDataEditSection.tsx
- portal/src/components/terminus/TerminusPoolView.tsx
- portal/src/components/terminus/TerminusPoolsListView.tsx
- portal/src/components/tokens/TokensList.tsx
- portal/src/contexts/AnalyticsContext/index.tsx
- portal/src/services/subscriptions.service.ts
Using ABI to fill 'name' parameter
Improving layout
Improving cache usage
Fixing some of Chakra's update consequences  
Fixing some of bugs caused by xdai's rename
> Analytics improvements

- portal/pages/features/index.tsx
- portal/src/components/FeatureCard.tsx
- portal/src/components/FeatureCardLarge.tsx
- portal/src/components/Landing.tsx
- portal/src/components/landing/MoonstreamMetrics.tsx
- portal/src/components/landing/TrustedBy.tsx
- portal/src/components/landing/UpcomingIntegrations.tsx
- portal/src/constants.ts
- portal/src/theme/foundations/colors.ts
> Landing update

- portal/src/components/ParamInput.tsx
Fixing white on white Select in Windows
> option style

- portal/src/components/layout.tsx
> optional request for login

- portal/src/components/leaderboard/LeaderboardPaginator.tsx
- portal/src/components/leaderboard/LeaderboardView.tsx
> pagination

- portal/pages/_app.tsx
- portal/pages/_document.tsx
- portal/src/components/FAQCard.tsx
- portal/src/components/FeatureCard.tsx
- portal/src/components/Footer.tsx
- portal/src/components/Landing.tsx
- portal/src/components/NeedAuthorizationView.tsx
- portal/src/components/SignIn.tsx
- portal/src/components/landing/LandingFAQ.tsx
- portal/src/components/landing/LandingFeaturedBy.tsx
- portal/src/components/landing/LandingFeatures.tsx
- portal/src/components/landing/LandingHeader.tsx
- portal/src/components/landing/LandingOpenSource.tsx
- portal/src/components/landing/LandingWorkflow.tsx
- portal/src/components/landing/MoonstreamMetrics.tsx
- portal/src/components/landing/TrustedBy.tsx
- portal/src/components/landing/UpcomingIntegrations.tsx
- portal/src/contexts/Web3Context/index.tsx
> Landing improvements

- portal/src/components/SignUp.tsx
- portal/src/hooks/useLogin.ts
- portal/src/hooks/useSignUp.tsx
signup and login error handling fix
> signup and login errors handling fix

- .gitignore
- portal/src/components/DropperClaimView.tsx
- portal/src/components/dropper/DropHeader.tsx
- portal/src/components/dropperV2/DropperV2ClaimsListItem.tsx
- portal/src/components/dropperV2/DropperV2DropView.tsx
- portal/src/components/dropperV2/DropperV2DropsList.tsx
- portal/src/components/dropperV2/DropperV2DropsListView.tsx
- portal/src/components/dropperV2/DropperV2View.tsx
- portal/src/components/dropperV2/JSONUpload.js
> Dropperv2 improvements

- portal/src/components/abiView/ABIFunctionModal.tsx
- portal/src/components/dropperV2/ActivateDropButton.tsx
- portal/src/components/dropperV2/DropperV2ChainDataEdit.tsx
- portal/src/components/dropperV2/DropperV2NewDrop.tsx
- portal/src/components/terminus/TerminusPoolView.tsx
- portal/src/components/terminus/TerminusPoolsListView.tsx
- portal/src/web3/contracts/types/types.ts
turning off 'Site suggested' gas price
> turning off 'Site suggested' gas price

- portal/sample.env
- portal/src/components/ChainSelector.tsx
- portal/src/components/analytics/AddressesPlaceholder.module.css
- portal/src/components/dropperV2/DropperV2NewDrop.tsx
- portal/src/styles/globals.css
- portal/src/web3/abi/MockTerminus.json
Also made some changes to `sample.env` to correctly reflect the variables used to configure the app.
> When creating a drop of type "Mint Terminus", the default drop URI is the Terminus pool URI

- portal/src/components/leaderboard/LeaderboardUpload.tsx
> Leaderboard admin

- portal/src/components/dropperV2/DropperV2DropsList.tsx
Fixing issue seen with dropper contract 0xb884bDD20e3A3D379209a197774b157E9fdB68F8 on polygon. (Multicall with too many queries.)
> Dropper multicall chunking

- portal/src/components/PoolDetailsRow.tsx
- portal/src/components/terminus/TerminusContractView.tsx
- portal/src/components/terminus/TerminusPoolView.tsx
- portal/src/components/terminus/TerminusPoolsListView.tsx
- portal/src/components/terminus/TerminusView.tsx
1. Adding copy button to all web3 addresses in PoolDetailsRow component
2. Terminus Page - changing layout for wide screens (removing width constrains)
3. Terminus Page - trim all web3 address inputs
> Improvements

- portal/src/components/leaderboard/LeaderboardAdminView.tsx
Filter leaderboards list by title and description
Selected list item style
> Leaderboard admin filter

- portal/src/components/SignIn.tsx
User should not be able to submit empty username or password
> handling empty fields

- portal/src/components/leaderboard/LeaderboardView.tsx
points_data can be any object, frontend flattens it
> Leaderboards fix

- portal/src/components/dropperV2/DropperV2ClaimantsUpload.tsx
- portal/src/components/dropperV2/DropperV2ContractView.tsx
- portal/src/components/dropperV2/DropperV2RegisterContractForm.tsx
typo
refetching after registering contract fix
> Dropper fixes

- portal/src/components/leaderboard/LeaderboardAdminView.tsx
- portal/src/components/leaderboard/NewLeaderboard.tsx
Correct selecting leaderboard in search results
> Leaderbords list fix

- portal/src/components/JSONEdit2.tsx
- portal/src/components/analytics/AnalyticsNewAddressView.tsx
Analytics - Watch New Address:
Selecting blockchain automatically only on first fetch of blockchains.
Disabling refetch of blockchains
Line numbers for ABI editor
> Analytics fixes

- portal/src/components/dropperV2/DropV2Data.tsx
- portal/src/components/dropperV2/DropperV2DropView.tsx
- portal/src/components/dropperV2/MintingApprovalInfo.tsx
- portal/src/components/terminus/TerminusPoolView.tsx
- portal/src/web3/abi/MockTerminus.json
- portal/src/web3/contracts/types/MockTerminus.ts
Drop of terminus tokens - Hiding 'Approve' button from those who are not Terminus pool controller, showing info instead
Direct update of drop state data after approving
Unapprove functionality for Terminus pool view
> Drop of terminus tokens fix
